mindmap
  root((Ambiente))
    [Parzialmente Accessibile]
    [Continuo]
    [Statico]
    [Episodico]
    [Deterministico]
    [Conosciuto]
    [Collaborazione Semplice]
    [Interazione Mediata da Artefatti]
